In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/mec02_data_centres.csv")
df

    Statistic Label Quarter              Electricity Consumption UNIT  VALUE
0    Gigawatt hours  2015Q1  All metered electricity consumption  GWh   6565
1    Gigawatt hours  2015Q1                         Data centres  GWh    291
2    Gigawatt hours  2015Q1    Customers other than data centres  GWh   6274
3    Gigawatt hours  2015Q2  All metered electricity consumption  GWh   6086
4    Gigawatt hours  2015Q2                         Data centres  GWh    304
..              ...     ...                                  ...  ...    ...
127  Gigawatt hours  2025Q3                         Data centres  GWh   1956
128  Gigawatt hours  2025Q3    Customers other than data centres  GWh   5778
129  Gigawatt hours  2025Q4  All metered electricity consumption  GWh   8420
130  Gigawatt hours  2025Q4                         Data centres  GWh   1991
131  Gigawatt hours  2025Q4    Customers other than data centres  GWh   6429

[132 rows x 5 columns]

In [3]:
wide = df.pivot(index="Quarter", columns = "Electricity Consumption", values= "VALUE",)
wide

Electricity Consumption,All metered electricity consumption,Customers other than data centres,Data centres
Quarter,,,
2015Q1,6565,6274,291
2015Q2,6086,5783,304
2015Q3,5783,5467,316
2015Q4,6165,5836,329
2016Q1,6651,6310,341
2016Q2,6471,6111,361
2016Q3,5926,5540,386
2016Q4,6307,5912,395
2017Q1,6867,6460,407
2017Q2,6429,5996,433
2017Q3,5969,5519,450
2017Q4,6461,5988,472
2018Q1,7097,6606,491
2018Q2,6845,6318,527
2018Q3,6187,5614,574
2018Q4,6601,6010,591
2019Q1,7128,6550,578
2019Q2,6349,5749,601
2019Q3,6299,5661,638
2019Q4,6728,6056,672
2020Q1,7399,6708,691
2020Q2,6429,5707,722
2020Q3,6381,5615,766
2020Q4,6847,5996,852
2021Q1,7347,6426,922
2021Q2,7222,6235,987
2021Q3,6779,5744,1035
2021Q4,7158,6089,1069
2022Q1,7847,6653,1194
2022Q2,7524,6237,1287
2022Q3,7050,5714,1336
2022Q4,7404,5948,1457
2023Q1,8038,6542,1497
2023Q2,7706,6152,1554
2023Q3,7136,5510,1625
2023Q4,7701,6038,1663
2024Q1,8348,6689,1659
2024Q2,7935,6243,1692
2024Q3,7513,5720,1793
2024Q4,8108,6278,1830
2025Q1,8706,6884,1821
2025Q2,8127,6232,1894
2025Q3,7734,5778,1956
2025Q4,8420,6429,1991

In [4]:
wide = wide.rename(columns={
    "All metered electricity consumption": "total",
    "Customers other than data centres": "others",
    "Data centres": "data_centres"
})
wide

Electricity Consumption  total  others  data_centres
Quarter
2015Q1                    6565    6274           291
2015Q2                    6086    5783           304
2015Q3                    5783    5467           316
2015Q4                    6165    5836           329
2016Q1                    6651    6310           341
2016Q2                    6471    6111           361
2016Q3                    5926    5540           386
2016Q4                    6307    5912           395
2017Q1                    6867    6460           407
2017Q2                    6429    5996           433
2017Q3                    5969    5519           450
2017Q4                    6461    5988           472
2018Q1                    7097    6606           491
2018Q2                    6845    6318           527
2018Q3                    6187    5614           574
2018Q4                    6601    6010           591
2019Q1                    7128    6550           578
2019Q2                    6349    5749           601
2019Q3                    6299    5661           638
2019Q4                    6728    6056           672
2020Q1                    7399    6708           691
2020Q2                    6429    5707           722
2020Q3                    6381    5615           766
2020Q4                    6847    5996           852
2021Q1                    7347    6426           922
2021Q2                    7222    6235           987
2021Q3                    6779    5744          1035
2021Q4                    7158    6089          1069
2022Q1                    7847    6653          1194
2022Q2                    7524    6237          1287
2022Q3                    7050    5714          1336
2022Q4                    7404    5948          1457
2023Q1                    8038    6542          1497
2023Q2                    7706    6152          1554
2023Q3                    7136    5510          1625
2023Q4                    7701    6038          1663
2024Q1                    8348    6689          1659
2024Q2                    7935    6243          1692
2024Q3                    7513    5720          1793
2024Q4                    8108    6278          1830
2025Q1                    8706    6884          1821
2025Q2                    8127    6232          1894
2025Q3                    7734    5778          1956
2025Q4                    8420    6429          1991

In [5]:
wide["dc_share"] = wide["data_centres"] / wide["total"] * 100
wide.round(1)

Electricity Consumption  total  others  data_centres  dc_share
Quarter
2015Q1                    6565    6274           291       4.4
2015Q2                    6086    5783           304       5.0
2015Q3                    5783    5467           316       5.5
2015Q4                    6165    5836           329       5.3
2016Q1                    6651    6310           341       5.1
2016Q2                    6471    6111           361       5.6
2016Q3                    5926    5540           386       6.5
2016Q4                    6307    5912           395       6.3
2017Q1                    6867    6460           407       5.9
2017Q2                    6429    5996           433       6.7
2017Q3                    5969    5519           450       7.5
2017Q4                    6461    5988           472       7.3
2018Q1                    7097    6606           491       6.9
2018Q2                    6845    6318           527       7.7
2018Q3                    6187    5614           574       9.3
2018Q4                    6601    6010           591       9.0
2019Q1                    7128    6550           578       8.1
2019Q2                    6349    5749           601       9.5
2019Q3                    6299    5661           638      10.1
2019Q4                    6728    6056           672      10.0
2020Q1                    7399    6708           691       9.3
2020Q2                    6429    5707           722      11.2
2020Q3                    6381    5615           766      12.0
2020Q4                    6847    5996           852      12.4
2021Q1                    7347    6426           922      12.5
2021Q2                    7222    6235           987      13.7
2021Q3                    6779    5744          1035      15.3
2021Q4                    7158    6089          1069      14.9
2022Q1                    7847    6653          1194      15.2
2022Q2                    7524    6237          1287      17.1
2022Q3                    7050    5714          1336      19.0
2022Q4                    7404    5948          1457      19.7
2023Q1                    8038    6542          1497      18.6
2023Q2                    7706    6152          1554      20.2
2023Q3                    7136    5510          1625      22.8
2023Q4                    7701    6038          1663      21.6
2024Q1                    8348    6689          1659      19.9
2024Q2                    7935    6243          1692      21.3
2024Q3                    7513    5720          1793      23.9
2024Q4                    8108    6278          1830      22.6
2025Q1                    8706    6884          1821      20.9
2025Q2                    8127    6232          1894      23.3
2025Q3                    7734    5778          1956      25.3
2025Q4                    8420    6429          1991      23.6

In [6]:
wide["year"] = wide.index.str[:4]
yearly = wide.groupby("year")[["data_centres", "others", "total"]].sum()
yearly["dc_share"] = yearly["data_centres"] / yearly["total"] * 100
yearly.round(1)

Electricity Consumption  data_centres  others  total  dc_share
year
2015                             1240   23360  24599       5.0
2016                             1483   23873  25355       5.8
2017                             1762   23963  25726       6.8
2018                             2183   24548  26730       8.2
2019                             2489   24016  26504       9.4
2020                             3031   24026  27056      11.2
2021                             4013   24494  28506      14.1
2022                             5274   24552  29825      17.7
2023                             6339   24242  30581      20.7
2024                             6974   24930  31904      21.9
2025                             7662   25323  32987      23.2

how fast did each group grow each year??

In [7]:

yearly["dc_growth"] = yearly["data_centres"].pct_change() * 100
yearly["others_growth"] = yearly["others"].pct_change() * 100
yearly.round(1)

Electricity Consumption,data_centres,others,total,dc_share,dc_growth,others_growth
year,,,,,,
2015,1240,23360,24599,5.0,NaN,NaN
2016,1483,23873,25355,5.8,19.6,2.2
2017,1762,23963,25726,6.8,18.8,0.4
2018,2183,24548,26730,8.2,23.9,2.4
2019,2489,24016,26504,9.4,14.0,-2.2
2020,3031,24026,27056,11.2,21.8,0.0
2021,4013,24494,28506,14.1,32.4,1.9
2022,5274,24552,29825,17.7,31.4,0.2
2023,6339,24242,30581,20.7,20.2,-1.3
2024,6974,24930,31904,21.9,10.0,2.8
2025,7662,25323,32987,23.2,9.9,1.6

2015 year shows it as NaN , because we dont have the 2014 data to compare the growth 

In 2025, share 23.2% - CSO says 23% 
         data centre growth 9.9% - CSO says 10 %
         others growth 1.6% - CSO says 2% 

Clearly , data centre demand grew upto 6 times faster than everyone else !!

IS it speeding up or slowing down ??

In 2021, the regulator restricted new data centre connections in Dublin

By reading the dc_growth, we can see :

 2016 to 2020 - the growth is fast!, 
 2021 and 2022 - PEAK [Fastest growth in whole dataset],
 2023 - Drops to 20%, 
 2024 and 2025 - About 10% a year.

### Growth is slowing down, and the slowdown starts right after the 2021 Dublin restrictions

### My honest takings here :

### 1. The timing is never the proof - 
slowdown matches the restrictions happened in 2021 , but it could also explain other things that happened in other years too ! 
### Other things could also explain the slowdown 
### The timing matches, but this data alone can't prove whether the restrictions caused the slowdown! 

### 2. Slower does not mean smaller - 
Growth slowed from 32% to 10%, but data centres still added about 690 GWh in 2025, and their share keeps rising every single year.
### The problem is growing more slowly, not going away.